### ISSUE TITLE
 levels plotted for 2Sigma & 3Sigma Expected moves for Daily Expected Moves

### ISSUE THREAD

**Issue by tostest123** [BennyKJohnson/TOSExpectedMoveStudies#1]
Hi Benny, 

This is an amazing indicator and its very price in terms of calculating the expected move. I understand the expected move is the 1sigma or (1Std Dev) but sometimes we might see closes greater than 1 std deviation. So would be great if we could also plot 2nd Std Dev (2sigma) & 3 Std Dev (3Sigma) expected move levels. that will be really helpful.

**Comment by BennyKJohnson** [comment]
Hi @tostest123,
Plotting the 2 and 3 sigma lines is fairly easy to do, I can add them for you.

**Comment by BennyKJohnson** [comment]
Added to Daily Expected Move script in 8c575ef
