### ISSUE TITLE
Errors when running main.py

### ISSUE THREAD

**Issue by Trumantester** [BennyKJohnson/TOSExpectedMoveStudies#4]
I am getting these errors when running Main.py :
No ThinkOrSwimCacheFileName specified. Found 2 cache files in directory
Found /Applications/thinkorswim/cache.6a4nrrvdrmmwpd9.tda.thinkorswim.com.xml cache file
Found /Applications/thinkorswim/cache.6a4nrrvdrmmwpd9.demo.thinkorswim.com.xml cache file
Using cache file /Applications/thinkorswim/cache.6a4nrrvdrmmwpd9.tda.thinkorswim.com.xml
Found 2 script entries
Downloading DailyExpectedMove at https://raw.githubusercontent.com/BennyKJohnson/TOSExpectedMoveStudies/master/DailyExpectedMoveSTUDY.ts...
Downloading WeeklyExpectedMove at https://raw.githubusercontent.com/BennyKJohnson/TOSExpectedMoveStudies/master/WeeklyExpectedMoveSTUDY.ts...
Updated contents of script {} DailyExpectedMove
Failed to find script with name WeeklyExpectedMove
Successfully updated /Applications/thinkorswim/cache.6a4nrrvdrmmwpd9.tda.thinkorswim.com.xml

Any idea why?
Thanks for any help.

**Comment by BennyKJohnson** [comment]
Hi,

The error means it couldn't locate the script with the name 'WeeklyExpectedMove'. The way the script works is it replaces the contents of existing scripts, it cannot install new scripts. 

You need to add a script manually with the name 'WeeklyExpectedMove'. Alternatively you can remove the entry "WeeklyExpectedMove = https://raw.githubusercontent.com/BennyKJohnson/TOSExpectedMoveStudies/master/WeeklyExpectedMoveSTUDY.ts" from the "scripts.ini".

**Comment by Trumantester** [comment]
I got that to work. After going down the rabbit hole of decoding the base64 cache file it was an easy fix that I thought I already did, but must of made some mistake with the study names. It worked after I deleted the one I had for the weekly expected moves and made a new one. 
Thank you.

**Comment by Trumantester** [comment]
That worked. After going down the rabbit hold of trying to decode the base64 encoded cache file, I tried deleting the daily expected move study and made a new one from scratch and it worked. I thought I had it named right but It must of been some error I made in naming and renaming the studies.
Thank You.
